# Generated by Django 5.1.1 on 2025-03-20 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre: ')),
                ('description', models.TextField(verbose_name='Descripción: ')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha creación: ')),
                ('edited_at', models.DateField(auto_now=True, verbose_name='Fecha edición: ')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre: ')),
                ('description', models.TextField(verbose_name='Descripción: ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio: ')),
                ('stock', models.IntegerField(verbose_name='Stock: ')),
                ('image', models.ImageField(default='null', upload_to='productos/', verbose_name='Imagen: ')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha creación: ')),
                ('edited_at', models.DateField(auto_now=True, verbose_name='Fecha edición: ')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria', verbose_name='Categoría: ')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Categorías',
            },
        ),
    ]
