# Generated by Django 5.1.1 on 2025-04-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_producto_options_alter_producto_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.BooleanField(default=False),
        ),
    ]
