# Generated by Django 5.1.1 on 2025-03-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre: ')),
                ('content', models.TextField(verbose_name='Contenido: ')),
                ('visible', models.BooleanField(verbose_name='¿Visible?')),
                ('slug', models.CharField(max_length=50, unique=True, verbose_name='Url amigable: ')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha creación: ')),
                ('edited_at', models.DateField(auto_now=True, verbose_name='Fecha edición: ')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
            },
        ),
    ]
